sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
- npm install -g mup

- openssl aes-256-cbc -k $KEY_PASSWORD
  -in secrets.tar.enc -out secrets.tar -d  # Decrypt secrets.tar.enc
- tar xvf secrets.tar # Decompress secrets.tar
services: mongodb
script:
- meteor update --release METEOR@1.2-rc.12
- meteor --test --settings settings.json --release velocity:METEOR@1.1.0.2_3
after_success:
- curl -L http://git.io/vqbln | sh